language: python
cache: pip
dist: trusty
python:
  - "3.6"
addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - libboost-system1.55-dev
      - libboost-filesystem1.55-dev
      - g++-4.8

before_install:
  - pip install pip --upgrade

install:
  # annoyingly we can't put this in setup.py...
  - pip install git+https://github.com/thedataincubator/expectexception.git@master
  - pip install -e .[test]

script:
  - pytest --cov -rfsxEX
  - pytest -rfsxEX --nbval ./notebooks --sanitize ./notebooks/tests_sanitize.cfg

after_success:
  - codecov
