language: python
cache: pip

python:
  - "3.6"
  - "3.7"

before_install:
  - pip install pip pytest --upgrade

install:
  - pip install -e .[tests]

script:
  - pytest --cov -rfsxEX
  - pytest -rfsxEX --nbval ./notebooks --sanitize ./notebooks/tests_sanitize.cfg

after_success:
  - codecov
